# Generated by Django 3.2.9 on 2022-01-26 10:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50, null=True)),
                ('Subject', models.CharField(max_length=50, null=True)),
                ('Details', ckeditor.fields.RichTextField(max_length=50, null=True)),
                ('Phone_no', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
