# Generated by Django 3.2.9 on 2022-01-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swifft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Username',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
