# Generated by Django 3.2.9 on 2022-01-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swifft', '0002_alter_contactus_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='Email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
