# Generated by Django 3.2.9 on 2022-01-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swifft', '0004_alter_contactus_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='Phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
